커뮤니티 UI, 마이페이지 UI
Team-Carea/Carea-Flutter pull request #7
Opened 2024-02-10 17:45 UTC by hanjeonghyun

## 📍 Issue 번호
closed #3 
closed #4 

## 🛠️ PR 세부 내용
하단 네비게이션 바 구현
커뮤니티 게시판 페이지
-> 마이페이지 연결
게시판 게시글 리스트
게시글 작성 페이지
세부 게시글 페이지

## 🚨 주의 사항
- 하단 바 구현 때문에 채팅방 리스트, 도움 찾기 페이지 임시 컴포넌트 생성
- Navigator 사용으로 app_routes 페이지의 코드 보류
- 일단은 반응형 고려 X (Pixel 6 기준 작성)

2024-02-11 18:20 UTC, Jjinyshin requested changes
view 파일들 파일명에 screen.dart로 끝나게 맞춰주세요~! 수고많으셨습니당💝

2024-02-11 18:20 UTC, Jinyshin commented on carea/lib/app/common/component/progress_bar.dart
> +              colors: <Color>[Color(0xffe5d6fa), Color(0xffc8dff8)],
이 색상들도 AppColors에 변수로 등록해서 사용해주세요!!

2024-02-11 18:20 UTC, Jjinyshin commented on carea/lib/app/modules/community/view/add_post.dart
> +class AddPost extends StatefulWidget {
view 폴더 내의 앱 뷰 파일, 위젯은 screen으로 끝나게 이름을 맞춰주세요!
수정 예시: create_post_screen.dart, CreatePostScreen
- 새로운 게시물을 추가한다는 의미에서 Add를 사용해도 괜찮지만, 새로운 게시물을 등록하는 건 보통 추가하는 느낌보단 새로 생성하는 느낌이기도 하고 CRUD의 C도 create이니까 단어를 변경했습니당

2024-02-11 18:20 UTC, Jjinyshin commented on carea/lib/app/common/component/category.dart
> +  {"text": "자유 게시판"},
위에 두 선택지 이름을
- "전체게시판"
- "자유게시판"
이렇게 바꾸는게 더 나을 것 같아요

2024-02-11 18:20 UTC, Jjinyshin commented on carea/lib/app/modules/community/view/post_list.dart
> +class Post {
이 부분은 추후 api 연결작업 할때 data 폴더 내부의 models 폴더로 이동시켜주세요~!

2024-02-12 03:57 UTC, hanjeonghyun commented
@Jjinyshin 7번 이슈 변경사항으로 모두 수정했습니다 :>
수정 과정에서 카테고리 선택 드랍다운 바와 post_detail_screen에 댓글 UI 추가했습니다!

2024-02-14 12:32 UTC, merged